//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eka.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eka.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Portions (C) International Organization for Standardization 1986
        ///     Permission to copy in any form is granted for use with
        ///     conforming SGML systems and applications as defined in
        ///     ISO 8879, provided this notice is included in all copies.
        ///--&gt;
        ///&lt;!-- Character entity set. Typical invocation:
        ///    &lt;!ENTITY % HTMLlat1 PUBLIC
        ///       &quot;-//W3C//ENTITIES Latin 1 for XHTML//EN&quot;
        ///       &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml-lat1.ent&quot;&gt;
        ///    %HTMLlat1;
        ///--&gt;
        ///
        ///&lt;!ENTITY nbsp   &quot;&amp;#160;&quot;&gt; &lt;!-- no-break space = non- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xhtml_lat1_ent {
            get {
                return ResourceManager.GetString("xhtml_lat1_ent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Special characters for XHTML --&gt;
        ///
        ///&lt;!-- Character entity set. Typical invocation:
        ///     &lt;!ENTITY % HTMLspecial PUBLIC
        ///        &quot;-//W3C//ENTITIES Special for XHTML//EN&quot;
        ///        &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml-special.ent&quot;&gt;
        ///     %HTMLspecial;
        ///--&gt;
        ///
        ///&lt;!-- Portions (C) International Organization for Standardization 1986:
        ///     Permission to copy in any form is granted for use with
        ///     conforming SGML systems and applications as defined in
        ///     ISO 8879, provided this notice is included in all copies.
        ///--&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xhtml_special_ent {
            get {
                return ResourceManager.GetString("xhtml_special_ent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Mathematical, Greek and Symbolic characters for XHTML --&gt;
        ///
        ///&lt;!-- Character entity set. Typical invocation:
        ///     &lt;!ENTITY % HTMLsymbol PUBLIC
        ///        &quot;-//W3C//ENTITIES Symbols for XHTML//EN&quot;
        ///        &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml-symbol.ent&quot;&gt;
        ///     %HTMLsymbol;
        ///--&gt;
        ///
        ///&lt;!-- Portions (C) International Organization for Standardization 1986:
        ///     Permission to copy in any form is granted for use with
        ///     conforming SGML systems and applications as defined in
        ///     ISO 8879, provided this notice is inclu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xhtml_symbol_ent {
            get {
                return ResourceManager.GetString("xhtml_symbol_ent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///   Extensible HTML version 1.0 Transitional DTD
        ///
        ///   This is the same as HTML 4 Transitional except for
        ///   changes due to the differences between XML and SGML.
        ///
        ///   Namespace = http://www.w3.org/1999/xhtml
        ///
        ///   For further information, see: http://www.w3.org/TR/xhtml1
        ///
        ///   Copyright (c) 1998-2002 W3C (MIT, INRIA, Keio),
        ///   All Rights Reserved. 
        ///
        ///   This DTD module is identified by the PUBLIC and SYSTEM identifiers:
        ///
        ///   PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;
        ///   SYSTEM &quot;http://www.w3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xhtml1_transitional_dtd {
            get {
                return ResourceManager.GetString("xhtml1_transitional_dtd", resourceCulture);
            }
        }
    }
}
